### ISSUE TITLE
OSError: libmklml_intel.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by madhav1ag** [dingjiansw101/RoITransformer_DOTA#2]
```
./train_dota_light_RoITransformer.sh 
experiments/faster_rcnn/../../faster_rcnn/config/config.py:175: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  exp_config = edict(yaml.load(f))
Traceback (most recent call last):
  File "experiments/faster_rcnn/rcnn_end2end_train_test_RoITransformer.py", line 17, in <module>
    import train_end2end_poly_RoITransformer
  File "experiments/faster_rcnn/../../faster_rcnn/train_end2end_poly_RoITransformer.py", line 44, in <module>
    import mxnet as mx
  File "/usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/base.py", line 213, in <module>
    _LIB = _load_lib()
  File "/usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmklml_intel.so: cannot open shared object file: No such file or directory

```

**Comment by dingjiansw101** [comment]
It seems that you intall the mxnet with mkl, but your system did not have the mkl. Furthermore, you did not check out to the required version of mxnet and build from source. Because we have own c++ operator, you must build from source, please follow the installation instructions.

**Comment by madhav1ag** [comment]
@dingjiansw101 
I have resolved this issue. But getting the following error : too many resources requested for launch

I am using 2080 TI GPU with CUDA 10

```
./train_dota_light_RoITransformer.sh 

experiments/faster_rcnn
experiments/faster_rcnn/../../faster_rcnn/config/config.py:175: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  exp_config = edict(yaml.load(f))
1
('Called with argument:', Namespace(cfg='experiments/faster_rcnn/cfgs/resnet_v1_101_dota_RoITransformer_trainval_rcnn_end2end.yaml', frequent=100))
['rois_output']
{'CLASS_AGNOSTIC': True,
 'MXNET_VERSION': 'mxnet',
 'SCALES': [(1024, 1024)],
 'TEST': {'BATCH_IMAGES': 1,
          'CXX_PROPOSAL': True,
          'HAS_RPN': True,
          'NMS': 0.3,
          'PROPOSAL_MIN_SIZE': 10,
          'PROPOSAL_NMS_THRESH': 0.7,
          'PROPOSAL_POST_NMS_TOP_N': 1000,
          'PROPOSAL_PRE_NMS_TOP_N': 20000,
          'RPN_MIN_SIZE': 10,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 1000,
          'RPN_PRE_NMS_TOP_N': 6000,
          'RRoI_MIN_SIZE': 10,
          'RRoI_NMS_THRESH': 0.5,
          'RRoI_POST_NMS_TOP_N': 1000,
          'RRoI_PRE_NMS_TOP_N': 1000,
          'max_per_image': 1000,
          'save_img_path': './debug/vis_debug_RoITransformer',
          'test_epoch': 40},
 'TRAIN': {'ALTERNATE': {'RCNN_BATCH_IMAGES': 0,
                         'RPN_BATCH_IMAGES': 0,
                         'rfcn1_epoch': 0,
                         'rfcn1_lr': 0,
                         'rfcn1_lr_step': '',
                         'rfcn2_epoch': 0,
                         'rfcn2_lr': 0,
                         'rfcn2_lr_step': '',
                         'rpn1_epoch': 0,
                         'rpn1_lr': 0,
                         'rpn1_lr_step': '',
                         'rpn2_epoch': 0,
                         'rpn2_lr': 0,
                         'rpn2_lr_step': '',
                         'rpn3_epoch': 0,
                         'rpn3_lr': 0,
                         'rpn3_lr_step': ''},
           'ASPECT_GROUPING': True,
           'BATCH_IMAGES': 1,
           'BATCH_ROIS': 512,
           'BATCH_ROIS_OHEM': 128,
           'BBOX_MEANS': [0.0, 0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZATION_PRECOMPUTED': True,
           'BBOX_REGRESSION_THRESH': 0.5,
           'BBOX_STDS': [0.1, 0.1, 0.2, 0.2, 0.05],
           'BBOX_WEIGHTS': array([1., 1., 1., 1., 1.]),
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'CXX_PROPOSAL': True,
           'ENABLE_OHEM': False,
           'END2END': True,
           'FG_FRACTION': 0.5,
           'FG_THRESH': 0.5,
           'FLIP': False,
           'RESUME': False,
           'RPN_BATCH_SIZE': 512,
           'RPN_BBOX_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 10,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 800,
           'RPN_PRE_NMS_TOP_N': 6000,
           'RRoI_BATCH_ROIS': 512,
           'RRoI_BATCH_ROIS_OHEM': 256,
           'RRoI_BBOX_MEANS': [0.0, 0.0, 0.0, 0.0, 0.0],
           'RRoI_BBOX_STDS': [0.05, 0.05, 0.1, 0.1, 0.025],
           'RRoI_ENABLE_OHEM': False,
           'RRoI_FG_FRACTION': 0.5,
           'RRoI_FG_THRESH': 0.5,
           'RRoI_MIN_SIZE': 10,
           'RRoI_NMS_THRESH': 0.5,
           'RRoI_POST_NMS_TOP_N': 800,
           'RRoI_PRE_NMS_TOP_N': 800,
           'RRoI_SCORE_THRESH': 0.0,
           'SHUFFLE': True,
           'begin_epoch': 0,
           'end_epoch': 40,
           'lr': 0.0005,
           'lr_factor': 0.1,
           'lr_step': '30,40',
           'model_prefix': 'rcnn_dota',
           'momentum': 0.9,
           'warmup': True,
           'warmup_lr': 5e-05,
           'warmup_step': 1000,
           'wd': 0.0005},
 'dataset': {'NUM_CLASSES': 16,
             'dataset': 'DOTA_oriented_v2',
             'dataset_path': 'data/dota_1024',
             'image_set': 'train',
             'proposal': 'rpn',
             'root_path': 'data/dota_1024',
             'test_image_set': 'test'},
 'default': {'frequent': 100, 'kvstore': 'device'},
 'gpus': '0',
 'network': {'ANCHOR_RATIOS': [0.5, 1, 2],
             'ANCHOR_SCALES': [4, 8, 16, 32, 64],
             'FIXED_PARAMS': ['conv1',
                              'bn_conv1',
                              'res2',
                              'bn2',
                              'gamma',
                              'beta'],
             'FIXED_PARAMS_SHARED': ['conv1',
                                     'bn_conv1',
                                     'res2',
                                     'bn2',
                                     'res3',
                                     'bn3',
                                     'res4',
                                     'bn4',
                                     'gamma',
                                     'beta'],
             'IMAGE_STRIDE': 0,
             'NUM_ANCHORS': 15,
             'PIXEL_MEANS': array([103.06, 115.9 , 123.15]),
             'RCNN_FEAT_STRIDE': 16,
             'RCNN_FG_AGNOSTIC': True,
             'RPN_FEAT_STRIDE': 16,
             'RRoI_CLASS_AGNOSTIC': False,
             'RRoI_REGRESSION': True,
             'pretrained': './model/pretrained_model/resnet_v1_101',
             'pretrained_epoch': 0},
 'output_path': './output/rcnn/DOTA',
 'symbol': 'resnet_v1_101_rcnn_light_head_RoITransformer'}
num_images 37334
DOTA_oriented_v2_train gt roidb loaded from data/dota_1024/cache/DOTA_oriented_v2_train_gt_roidb.pkl
filtered 9375 roidb entries: 37334 -> 27959
providing maximum shape [('data', (1, 3, 1024, 1024)), ('gt_boxes', (1, 100, 9))] [('label', (1, 61440)), ('bbox_target', (1, 60, 64, 64)), ('bbox_weight', (1, 60, 64, 64))]
{'bbox_target': (1, 60, 64, 64),
 'bbox_weight': (1, 60, 64, 64),
 'data': (1, 3, 1024, 1024),
 'gt_boxes': (1, 7, 9),
 'im_info': (1, 3),
 'label': (1, 61440)}
('lr', 0.0005, 'lr_epoch_diff', [30.0, 40.0], 'lr_iters', [838770, 1118360])
[13:56:42] /opt/github/mxnet/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "experiments/faster_rcnn/rcnn_end2end_train_test_RoITransformer.py", line 35, in <module>
    train_end2end_poly_RoITransformer.main()
  File "experiments/faster_rcnn/../../faster_rcnn/train_end2end_poly_RoITransformer.py", line 181, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "experiments/faster_rcnn/../../faster_rcnn/train_end2end_poly_RoITransformer.py", line 174, in train_net
    arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "experiments/faster_rcnn/../../faster_rcnn/core/module.py", line 989, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "experiments/faster_rcnn/../../faster_rcnn/core/module.py", line 1081, in update_metric
    self._curr_module.update_metric(eval_metric, labels)
  File "experiments/faster_rcnn/../../faster_rcnn/core/module.py", line 672, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "experiments/faster_rcnn/../../faster_rcnn/core/DataParallelExecutorGroup.py", line 481, in update_metric
    eval_metric.update(labels, texec.outputs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/metric.py", line 364, in update
    metric.update(labels, preds)
  File "experiments/faster_rcnn/../../faster_rcnn/core/metric.py", line 55, in update
    pred_label = mx.ndarray.argmax_channel(pred).asnumpy().astype('int32')
  File "/usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/ndarray/ndarray.py", line 1996, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [13:56:47] /opt/github/mxnet/src/operator/contrib/proposal.cu:497: Check failed: error == cudaSuccess (7 vs. 0) :  too many resources requested for launch
Stack trace:
  [bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x32) [0x7ff187b1ba32]
  [bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/libmxnet.so(mxnet::op::ProposalGPUOp<mshadow::gpu>::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x15a0) [0x7ff18b1bd480]
  [bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/libmxnet.so(mxnet::op::OperatorState::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x500) [0x7ff18988c2b0]
  [bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/libmxnet.so(mxnet::exec::StatefulComputeExecutor::Run(mxnet::RunContext, bool)+0xe8) [0x7ff1899b4158]
  [bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/libmxnet.so(+0x2f3d7df) [0x7ff1899777df]
  [bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/libmxnet.so(mxnet::engine::ThreadedEngine::ExecuteOprBlock(mxnet::RunContext, mxnet::engine::OprBlock*)+0x577) [0x7ff189842d67]
  [bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/libmxnet.so(void mxnet::engine::ThreadedEnginePerDevice::GPUWorker<(dmlc::ConcurrentQueueType)0>(mxnet::Context, bool, mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<(dmlc::ConcurrentQueueType)0>*, std::shared_ptr<dmlc::ManualEvent> const&)+0x11d) [0x7ff18984cd6d]
  [bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/libmxnet.so(std::_Function_handler<void (std::shared_ptr<dmlc::ManualEvent>), mxnet::engine::ThreadedEnginePerDevice::PushToExecute(mxnet::engine::OprBlock*, bool)::{lambda()#4}::operator()() const::{lambda(std::shared_ptr<dmlc::ManualEvent>)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<dmlc::ManualEvent>&&)+0x4e) [0x7ff18984d02e]
  [bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet-1.5.0-py2.7.egg/mxnet/libmxnet.so(std::thread::_Impl<std::_Bind_simple<std::function<void (std::shared_ptr<dmlc::ManualEvent>)> (std::shared_ptr<dmlc::ManualEvent>)> >::_M_run()+0x4a) [0x7ff189841d4a]
```

**Comment by fl82hope** [comment]
I also use cuda10, encounter similar error: 
Traceback (most recent call last):
  File "experiments/faster_rcnn/rcnn_end2end_train_test_RoITransformer.py", line 17, in <module>
    import train_end2end_poly_RoITransformer
  File "experiments/faster_rcnn/../../faster_rcnn/train_end2end_poly_RoITransformer.py", line 25, in <module>
    import mxnet as mx
  File "/home/fulan/.local/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/fulan/.local/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/base.py", line 52, in <module>
    _LIB = _load_lib()
  File "/home/fulan/.local/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/base.py", line 44, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.8.0: cannot open shared object file: No such file or directory

Did you use cuda 8.0?

**Comment by dingjiansw101** [comment]
We only tested on cuda 8 before. And we have not tested on cuda 10, not sure if it is the reason.
