### ISSUE TITLE
What is the cuda and cudnn required for this repo ?

### ISSUE THREAD

**Issue by dexception** [dingjiansw101/RoITransformer_DOTA#5]
What is the cuda and cudnn required for this repo ?

**Comment by dingjiansw101** [comment]
We tested on cuda 8. Cudnn compatible with cuda 8 should be ok.

**Comment by dexception** [comment]
Tried with cuda 9 ... it does not work. I am unable to compile mxnet.

**Comment by oceanleftsea** [comment]
what's your specific problem? I also fail to compile mxnet with cuda 9.The following is my problem:

/usr/local/cuda/include/crt/common_functions.h:64:24: error: token ""__CUDACC_VER__ is no longer supported.

**Comment by dexception** [comment]
@oceanleftsea 
Yes same CUDACC_VER  error.

**Comment by dingjiansw101** [comment]
The driver may be too high. We use 3.9 nvidia driver.

**Comment by DetectionIIT** [comment]
I am also unable to compile mxnet successfully! .Have you solved this?@dexception@oceanleftsea

(py27) gu@iitlab-cat:~/mxnet/python$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    LIB_PATH = libinfo['find_lib_path']()
  File "mxnet/libinfo.py", line 42, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the files.
List of candidates:
/home/disk2/mxnet/python/mxnet/libmxnet.so
/home/disk2/mxnet/python/mxnet/../../lib/libmxnet.so
/home/disk2/mxnet/python/mxnet/../../build/Release/libmxnet.so
../../../libmxnet.so

**Comment by dexception** [comment]
@DetectionIIT 
Not even trying this repo. Its buggy and not updated.

**Comment by jaminChen999** [comment]
@DetectionIIT I have the same problem, You fixed that ?
